version: 2.1

executors:
  executor1:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD 
jobs:  
  build_push_image:
    circleci_ip_ranges: true 
    executor: executor1
    steps:
      - checkout
      - setup_remote_docker
   
   
      - run: 
          name: build_image
          command:  |         
            echo $DOCKERHUB_PASSWORD   | docker login -u $DOCKERHUB_USERNAME --password-stdin 
            docker build -t beknazar007/to_do_image  .              
            docker push beknazar007/to_do_image:latest

  deploy_to_GKE:  
    
    docker:
      - image: google/cloud-sdk
    environment:
            PROJECT_NAME: "to-do-app"
            GOOGLE_PROJECT_ID: circle-ci-demo-343616
            GOOGLE_COMPUTE_ZONE: "us-central1-a"
            GOOGLE_CLUSTER_NAME: "cluster-1"




    steps:
       - checkout
       - run:
          name: Install helm
          command: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh  
            ./get_helm.sh
       - run: 
          name: Setup Google Cloud SDK
          command: | 
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            
            # envsubst < ${HOME}/project/Chart-ToDo_App > ${HOME}/Chart-ToDo_App
            
            kubectl apply -f deployment.yaml
            echo "Ishtedi "

            helm install chart1 Chart-ToDo_App/

workflows:
  to_do_app:
    jobs:
      - build_push_image:
          context: docker-cred
          
      - deploy_to_GKE:
          requires:
            - build_push_image 
      
      
      
  
